# Table Of Contents

- Using Numpy
    - List and Array Performance Comparison
    - Numpy Arrays
    - Array Attributes and Methods
    - Dimension and Shapes
- Numpy Indexing and Selection
    - Bracket Indexing and Selection
    - Indexing a 2D array
    - Selection
- NumPy Operations

# Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np
import pandas as pd

---
Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_matrix*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array(my_matrix)*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.array(my_matrix).dtype

dtype('int64')

In [ ]:
np.random.rand(2)

array([0.46277967, 0.20156842])

In [ ]:
np.random.rand(5,5)

array([[0.1805737 , 0.36245194, 0.38725345, 0.06598235, 0.69838183],
       [0.18056184, 0.5052644 , 0.66468253, 0.45106236, 0.42699765],
       [0.95207417, 0.98722406, 0.73809246, 0.21427794, 0.78606951],
       [0.03761925, 0.44358861, 0.86580336, 0.05584263, 0.87124401],
       [0.60509522, 0.20441472, 0.8728795 , 0.27960837, 0.38031307]])

---
## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([10,  6, 41,  0,  7,  0, 35, 48, 26, 18])

In [ ]:
arr.reshape(5,5) #mengubah ke bentuk matriks berukuran 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

array([10,  6, 41,  0,  7,  0, 35, 48, 26, 18])

In [ ]:
ranarr.max()

48

In [ ]:
np.max(ranarr)

48

In [ ]:
ranarr.argmax() #mencari index keberapa nilai max nya

7

In [ ]:
ranarr.min()

0

In [ ]:
ranarr.argmin() #mencari index keberapa nilai min nya

3

---
## Dimensions and Shapes

`ndim`, `size`, and `shape`

- Shape is an attribute that arrays have (not a method)
- `ndim` returns the array dimension
- `size` returns the number of elements in the array

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
type(C[0])

list

# NumPy Indexing and Selection

## Bracket Indexing and Selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[-4:]

array([ 7,  8,  9, 10])

In [ ]:
#Get values in a range
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[1:3]

array([1, 2])

In [ ]:
arr[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array (matrices)

The general format are: 
- **arr_2d[row][col]** or 
- **arr_2d[row,col]**.

I recommend usually using the comma notation for clarity.

Similar with Python List, array index also start from 0

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

In [ ]:
#Shape bottom row
arr_2d[2,:]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr<6]

In [ ]:
x = 2
arr[arr>x]

# NumPy Operations

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr

In [ ]:
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
A.sum(axis=1)

In [ ]:
A.sum(axis=0)

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

In [ ]:
B.T